/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Full quality analysis. Returns a Promise<IqaResult>. */
export declare function analyze(buffer: Buffer): Promise<unknown>

export interface IqaResult {
  /**
   * BRISQUE-based quality score in [0, 100].  Lower = better.
   *   0–20  Excellent
   *  20–40  Good
   *  40–60  Acceptable
   *  60+    Poor
   */
  score: number
  /** Human-readable quality label: "excellent" | "good" | "acceptable" | "poor" */
  quality: string
  /** True when Laplacian variance indicates motion/focus blur. */
  isBlurry: boolean
  /** Exposure assessment: "normal" | "underexposed" | "overexposed" */
  exposure: string
  /** Noise estimate: "low" | "medium" | "high" */
  noiseLevel: string
  /** List of human-readable warnings (empty for clean images). */
  warnings: Array<string>
}

/** Returns only the numeric BRISQUE score. Slightly faster than analyze(). */
export declare function quickScore(buffer: Buffer): Promise<unknown>

/**
 * Analyze a batch of images in parallel.
 * Returns a Promise<IqaResult[]> in the same order as input.
 */
export declare function scoreBatch(buffers: Array<Buffer>): Promise<unknown>

/** Validates an image against configurable quality thresholds. */
export declare function validate(buffer: Buffer, options?: ValidationOptions | undefined | null): Promise<unknown>

export interface ValidationOptions {
  /** Reject images with score above this threshold (lower = stricter). */
  minScore?: number
  /** Reject blurry images when true. */
  rejectBlurry?: boolean
  /** Reject non-normal exposures when true. */
  rejectBadExposure?: boolean
}

export interface ValidationResult {
  passed: boolean
  score: number
  quality: string
  failures: Array<string>
}
